services:
  plantuml:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    ports:
      - "8080:8080"
    volumes:
      - ./docs/docs/diagrams/include:/include
    environment:
      - PLANTUML_INCLUDE_PATH=/include
    restart: unless-stopped
    networks:
      - warm-house-docs-network

  mkdocs:
    build:
      context: .
    container_name: warm-house-mkdocs
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/docs
    depends_on:
      - plantuml
    networks:
      - warm-house-docs-network

networks:
  warm-house-docs-network:
    driver: bridge